spring.application.name=backend

spring.datasource.url=jdbc:postgresql://YOUR_DATABASE_HOST:5432/postgres?sslmode=require
spring.datasource.username=YOUR_DATABASE_USERNAME
spring.datasource.password=YOUR_DATABASE_PASSWORD

google.maps.api.key=YOUR_GOOGLE_MAPS_API_KEY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
